services:
  - type: web
    name: pii-guardian-backend
    env: docker
    plan: free
    branch: main
    region: oregon
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SECRET_KEY
        sync: false   # set manually in Render Dashboard
